package org.jworkflow.observability;

public enum WorkflowLifecycleEventType {
    WORKFLOW_STARTED,
    WORKFLOW_COMPLETED,
    WORKFLOW_FAILED,
    STEP_ENTERED,
    STEP_COMPLETED,
    STEP_FAILED,
    TRANSITION_TAKEN,
    EVENT_RECEIVED,
    EVENT_CORRELATED,
    EVENT_IGNORED,
    RETRY_SCHEDULED,
    TIMER_FIRED,
    OUTBOX_CREATED,
    OUTBOX_PUBLISHED,
    OUTBOX_PUBLICATION_FAILED,
    INBOX_DEAD_LETTERED
}
