package org.jworkflow.workbench;

import java.io.IOException;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Builds the complete source change set for one generated workflow (WB-14): the Groovy definition, a command record
 * for each missing step action, and a listener per action that translates the step's event context into its command.
 * Listeners implement the pinned core {@code StepHandler} and hand the command to a user-supplied {@code Consumer}, so
 * service wiring stays with the user (INT-01). User-written or user-modified Java is never rewritten.
 */
final class SourceIntegration {
    static final String GENERATED_MARKER = "Generated by JWorkflow Workbench";
    private static final Pattern IMPORT = Pattern.compile("(?m)^\\s*import\\s+([\\w.]+(?:\\.\\*)?)\\s*;");
    private static final Pattern TYPE = Pattern.compile("[A-Za-z_$][\\w$.]*(<[\\w$.<>?, \\[\\]]+>)?(\\[])*");
    private static final Map<String, String> NUMERIC = Map.of("int", "intValue", "long", "longValue", "double", "doubleValue",
            "float", "floatValue", "short", "shortValue", "byte", "byteValue");

    @FunctionalInterface interface Sources { String read(String relative) throws IOException; }

    /** One reviewed artifact; {@code status} is create, update, unchanged or kept (user-owned, not rewritten). */
    record Artifact(String kind, String action, String className, String path, String status, List<String> mapping, String note) {}
    record Result(List<ChangeSetStore.FileChange> changes, List<Artifact> artifacts, List<String> discrepancies, String groovyPath, boolean manualGroovyEdit) {}

    private SourceIntegration() {}

    /**
     * @param appliedHashes hashes Workbench recorded when it last applied each path; a file is Workbench-owned only
     *                      while its current hash still matches
     */
    static Result build(ProjectWorkspace.DraftView draft, String groovy, List<ProjectWorkspace.Binding> bindings,
            Map<String, String> appliedHashes, Sources sources) throws IOException {
        List<ChangeSetStore.FileChange> changes = new ArrayList<>();
        List<Artifact> artifacts = new ArrayList<>();
        List<String> discrepancies = new ArrayList<>();
        String groovyPath = draft.outputDirectory() + "/" + draft.engineId() + ".groovy";
        String currentGroovy = sources.read(groovyPath);
        boolean manual = currentGroovy != null && !currentGroovy.equals(groovy)
                && !ChangeSetStore.FileChange.hash(currentGroovy).equals(appliedHashes.get(groovyPath));
        add(changes, artifacts, "workflow", "", draft.engineId() + ".groovy", groovyPath, currentGroovy, groovy, List.of(),
                manual ? "The existing file differs from what Workbench last wrote; replacing it needs your confirmation." : "");
        if (manual) discrepancies.add("`" + groovyPath + "` was edited outside Workbench. Workbench does not import manual Groovy edits; approving replaces it with the generated definition.");

        for (String action : WorkflowGenerationService.stepActions(draft.blockly())) {
            ProjectWorkspace.Binding command = bindings.stream().filter(b -> b.role().equals("command")
                    && (b.name().equals(action) || qualified(b).equals(action))).findFirst().orElse(null);
            String commandPackage, commandName;
            List<ProjectWorkspace.Field> fields;
            List<String> imports;
            if (command != null) {
                commandPackage = command.packageName(); commandName = command.name(); fields = command.fields();
                String source = sources.read(command.source());
                artifacts.add(new Artifact("command", action, qualified(command), command.source(), "kept", fieldNames(fields), "Existing command; Workbench does not change it."));
                if (source == null || !Pattern.compile("\\brecord\\s+" + Pattern.quote(commandName) + "\\b").matcher(source).find()) {
                    discrepancies.add("Command `" + qualified(command) + "` is not a record, so Workbench cannot infer how to construct it. Write the listener for action `" + action + "` yourself, or convert the command to a record.");
                    continue;
                }
                imports = imports(source);
            } else {
                if (!WorkflowGenerationService.isJavaIdentifier(action) || draft.javaPackage().isBlank()) continue;
                commandPackage = draft.javaPackage(); commandName = action;
                fields = List.of(new ProjectWorkspace.Field("String", "businessKey"), new ProjectWorkspace.Field("Map<String, Object>", "variables"));
                imports = List.of("java.util.Map");
                String path = javaPath(commandPackage, commandName), current = sources.read(path);
                String created = commandRecord(commandPackage, commandName, draft.engineId());
                if (current != null && !current.equals(created)) {
                    artifacts.add(new Artifact("command", action, commandPackage + "." + commandName, path, "kept", List.of(), "A file already exists here but was not discovered as a command; it was left unchanged."));
                    discrepancies.add("`" + path + "` exists but does not implement `org.jworkflow.application.Command`. Workbench left it unchanged; make it a command record or choose another action name.");
                    continue;
                }
                add(changes, artifacts, "command", action, commandPackage + "." + commandName, path, current, created, fieldNames(fields), "New command record (INT-01 missing-command creation).");
            }

            List<String> mapping = new ArrayList<>();
            List<String> arguments = new ArrayList<>();
            boolean unchecked = false, ambiguous = false;
            for (ProjectWorkspace.Field field : fields) {
                String expression = expression(field);
                if (expression == null) { ambiguous = true; discrepancies.add("Field `" + field.name() + "` of `" + commandName + "` has a type (`" + field.type() + "`) Workbench cannot map from step variables; write that conversion in the listener yourself."); continue; }
                unchecked |= expression.startsWith("(" + field.type()) && field.type().contains("<");
                arguments.add(expression);
                mapping.add(field.name() + " ← " + describe(field));
            }
            String listenerName = commandName + "Listener";
            String listenerPath = javaPath(commandPackage, listenerName);
            String currentListener = sources.read(listenerPath);
            if (ambiguous) {
                artifacts.add(new Artifact("listener", action, commandPackage + "." + listenerName, listenerPath, currentListener == null ? "not generated" : "kept", mapping, "Not generated: some command fields need a conversion you choose."));
                continue;
            }
            String listener = listener(commandPackage, listenerName, commandName, draft.engineId(), action, usedImports(imports, fields), arguments, unchecked);
            boolean owned = currentListener == null || currentListener.equals(listener)
                    || ChangeSetStore.FileChange.hash(currentListener).equals(appliedHashes.get(listenerPath));
            if (!owned) {
                artifacts.add(new Artifact("listener", action, commandPackage + "." + listenerName, listenerPath, "kept", mapping, "Existing listener was written or changed by you; Workbench left it unchanged."));
                discrepancies.add("`" + listenerPath + "` was written or edited outside Workbench and was not changed. Check that it implements `StepHandler` for action `" + action + "` and maps: " + String.join("; ", mapping) + ".");
                continue;
            }
            add(changes, artifacts, "listener", action, commandPackage + "." + listenerName, listenerPath, currentListener, listener, mapping, "Translates the step's event context into " + commandName + ".");
        }
        return new Result(List.copyOf(changes), List.copyOf(artifacts), List.copyOf(discrepancies), groovyPath, manual);
    }

    private static void add(List<ChangeSetStore.FileChange> changes, List<Artifact> artifacts, String kind, String action, String className,
            String path, String before, String after, List<String> mapping, String note) {
        String status = before == null ? "create" : before.equals(after) ? "unchanged" : "update";
        if (!status.equals("unchanged")) changes.add(new ChangeSetStore.FileChange(path, before, after));
        artifacts.add(new Artifact(kind, action, className, path, status, mapping, note));
    }

    static String commandRecord(String packageName, String name, String engineId) {
        return "package " + packageName + ";\n\n"
                + "import java.util.Collections;\n"
                + "import java.util.LinkedHashMap;\n"
                + "import java.util.Map;\n"
                + "import org.jworkflow.application.Command;\n\n"
                + "/**\n"
                + " * Command for step action {@code " + name + "} in workflow {@code " + engineId + "}, created by JWorkflow Workbench.\n"
                + " * Add the fields your service needs; Workbench maps record components from step variables by name.\n"
                + " */\n"
                + "public record " + name + "(String businessKey, Map<String, Object> variables) implements Command {\n"
                + "    public " + name + " {\n"
                + "        variables = variables == null ? Map.of() : Collections.unmodifiableMap(new LinkedHashMap<>(variables));\n"
                + "    }\n"
                + "}\n";
    }

    static String listener(String packageName, String className, String commandName, String engineId, String action,
            List<String> commandImports, List<String> arguments, boolean unchecked) {
        TreeSet<String> imports = new TreeSet<>(List.of("java.util.Objects", "java.util.function.Consumer",
                "org.jworkflow.engine.StepContext", "org.jworkflow.engine.StepHandler", "org.jworkflow.engine.StepResult"));
        for (String value : commandImports) if (!value.equals("org.jworkflow.application.Command")) imports.add(value);
        StringBuilder out = new StringBuilder("package ").append(packageName).append(";\n\n");
        for (String value : imports) out.append("import ").append(value).append(";\n");
        out.append("\n/**\n")
                .append(" * ").append(GENERATED_MARKER).append(" for workflow {@code ").append(engineId).append("}, step action {@code ").append(action).append("}.\n")
                .append(" * Translates the event context that reaches the step into {@link ").append(commandName).append("} and hands it to the service\n")
                .append(" * call you supply, for example {@code builder.stepHandler(\"").append(action).append("\", new ").append(className).append("(service::handle))}.\n")
                .append(" * A runtime exception from that call becomes a step failure, which follows the workflow's failure route.\n")
                .append(" * Workbench updates this file only while it is unchanged since Workbench last wrote it.\n")
                .append(" */\n")
                .append("public final class ").append(className).append(" implements StepHandler {\n")
                .append("    private final Consumer<? super ").append(commandName).append("> dispatcher;\n\n")
                .append("    public ").append(className).append("(Consumer<? super ").append(commandName).append("> dispatcher) {\n")
                .append("        this.dispatcher = Objects.requireNonNull(dispatcher, \"dispatcher\");\n")
                .append("    }\n\n")
                .append("    @Override\n")
                .append("    public StepResult handle(StepContext context) {\n")
                .append("        try {\n")
                .append("            dispatcher.accept(toCommand(context));\n")
                .append("            return StepResult.success();\n")
                .append("        } catch (RuntimeException failure) {\n")
                .append("            return StepResult.failure(failure.getClass().getSimpleName(), String.valueOf(failure.getMessage()));\n")
                .append("        }\n")
                .append("    }\n\n");
        if (unchecked) out.append("    @SuppressWarnings(\"unchecked\")\n");
        out.append("    static ").append(commandName).append(" toCommand(StepContext context) {\n")
                .append("        return new ").append(commandName).append("(");
        if (arguments.isEmpty()) out.append(");\n");
        else out.append("\n                ").append(String.join(",\n                ", arguments)).append(");\n");
        out.append("    }\n}\n");
        return out.toString();
    }

    /** Java expression reading one record component from the step context, or null when the conversion is ambiguous. */
    static String expression(ProjectWorkspace.Field field) {
        String type = field.type().strip(), name = field.name();
        if (!TYPE.matcher(type).matches() || !WorkflowGenerationService.isJavaIdentifier(name)) return null;
        if (name.equals("businessKey") && type.equals("String")) return "context.businessKey()";
        if (name.equals("variables") && type.replace(" ", "").matches("(java\\.util\\.)?Map<String,Object>")) return "context.variables()";
        String value = "context.variables().get(\"" + name + "\")";
        if (NUMERIC.containsKey(type)) return "((Number) " + value + ")." + NUMERIC.get(type) + "()";
        if (type.equals("boolean")) return "(Boolean) " + value;
        if (type.equals("char")) return null;
        return "(" + type + ") " + value;
    }

    private static String describe(ProjectWorkspace.Field field) {
        if (field.name().equals("businessKey") && field.type().equals("String")) return "workflow business key";
        if (field.name().equals("variables") && field.type().replace(" ", "").endsWith("Map<String,Object>")) return "all workflow variables";
        return "variables[\"" + field.name() + "\"] as " + field.type();
    }

    private static List<String> imports(String source) {
        List<String> values = new ArrayList<>(); Matcher m = IMPORT.matcher(source);
        while (m.find()) values.add(m.group(1));
        return values;
    }
    /** Only the command's imports that the mapped field types refer to (wildcards are kept), so output stays stable. */
    private static List<String> usedImports(List<String> imports, List<ProjectWorkspace.Field> fields) {
        String types = fields.stream().map(ProjectWorkspace.Field::type).reduce("", (a, b) -> a + " " + b);
        return imports.stream().filter(value -> value.endsWith(".*")
                || Pattern.compile("\\b" + Pattern.quote(value.substring(value.lastIndexOf('.') + 1)) + "\\b").matcher(types).find()).toList();
    }
    private static List<String> fieldNames(List<ProjectWorkspace.Field> fields) { return fields.stream().map(f -> f.type() + " " + f.name()).toList(); }
    private static String qualified(ProjectWorkspace.Binding binding) { return binding.packageName().isBlank() ? binding.name() : binding.packageName() + "." + binding.name(); }
    static String javaPath(String packageName, String className) {
        return "src/main/java/" + (packageName.isBlank() ? "" : packageName.replace('.', '/') + "/") + className + ".java";
    }
}
