-- Rewrites stored Instant text to a fixed nine-digit fraction (yyyy-MM-ddTHH:mm:ss.nnnnnnnnnZ).
-- Instant.toString() drops or shortens the fraction, so text order did not match time order.
-- Only four-digit-year UTC values whose length differs from the fixed 30-character form are rewritten.
update workflow_definition set created_at=substr(created_at,1,19)||'.'||substr((case when substr(created_at,20,1)='.' then substr(created_at,21,length(created_at)-21) else '' end)||'000000000',1,9)||'Z' where created_at is not null and length(created_at)<>30 and created_at like '____-__-__T__:__:__%Z';
update workflow_definition set updated_at=substr(updated_at,1,19)||'.'||substr((case when substr(updated_at,20,1)='.' then substr(updated_at,21,length(updated_at)-21) else '' end)||'000000000',1,9)||'Z' where updated_at is not null and length(updated_at)<>30 and updated_at like '____-__-__T__:__:__%Z';
update workflow_instance set created_at=substr(created_at,1,19)||'.'||substr((case when substr(created_at,20,1)='.' then substr(created_at,21,length(created_at)-21) else '' end)||'000000000',1,9)||'Z' where created_at is not null and length(created_at)<>30 and created_at like '____-__-__T__:__:__%Z';
update workflow_instance set updated_at=substr(updated_at,1,19)||'.'||substr((case when substr(updated_at,20,1)='.' then substr(updated_at,21,length(updated_at)-21) else '' end)||'000000000',1,9)||'Z' where updated_at is not null and length(updated_at)<>30 and updated_at like '____-__-__T__:__:__%Z';
update workflow_event set occurred_at=substr(occurred_at,1,19)||'.'||substr((case when substr(occurred_at,20,1)='.' then substr(occurred_at,21,length(occurred_at)-21) else '' end)||'000000000',1,9)||'Z' where occurred_at is not null and length(occurred_at)<>30 and occurred_at like '____-__-__T__:__:__%Z';
update workflow_event set received_at=substr(received_at,1,19)||'.'||substr((case when substr(received_at,20,1)='.' then substr(received_at,21,length(received_at)-21) else '' end)||'000000000',1,9)||'Z' where received_at is not null and length(received_at)<>30 and received_at like '____-__-__T__:__:__%Z';
update event_status set next_retry_at=substr(next_retry_at,1,19)||'.'||substr((case when substr(next_retry_at,20,1)='.' then substr(next_retry_at,21,length(next_retry_at)-21) else '' end)||'000000000',1,9)||'Z' where next_retry_at is not null and length(next_retry_at)<>30 and next_retry_at like '____-__-__T__:__:__%Z';
update event_status set created_at=substr(created_at,1,19)||'.'||substr((case when substr(created_at,20,1)='.' then substr(created_at,21,length(created_at)-21) else '' end)||'000000000',1,9)||'Z' where created_at is not null and length(created_at)<>30 and created_at like '____-__-__T__:__:__%Z';
update workflow_inbox set received_at=substr(received_at,1,19)||'.'||substr((case when substr(received_at,20,1)='.' then substr(received_at,21,length(received_at)-21) else '' end)||'000000000',1,9)||'Z' where received_at is not null and length(received_at)<>30 and received_at like '____-__-__T__:__:__%Z';
update workflow_inbox set processed_at=substr(processed_at,1,19)||'.'||substr((case when substr(processed_at,20,1)='.' then substr(processed_at,21,length(processed_at)-21) else '' end)||'000000000',1,9)||'Z' where processed_at is not null and length(processed_at)<>30 and processed_at like '____-__-__T__:__:__%Z';
update workflow_inbox set next_attempt_at=substr(next_attempt_at,1,19)||'.'||substr((case when substr(next_attempt_at,20,1)='.' then substr(next_attempt_at,21,length(next_attempt_at)-21) else '' end)||'000000000',1,9)||'Z' where next_attempt_at is not null and length(next_attempt_at)<>30 and next_attempt_at like '____-__-__T__:__:__%Z';
update workflow_inbox set claim_until=substr(claim_until,1,19)||'.'||substr((case when substr(claim_until,20,1)='.' then substr(claim_until,21,length(claim_until)-21) else '' end)||'000000000',1,9)||'Z' where claim_until is not null and length(claim_until)<>30 and claim_until like '____-__-__T__:__:__%Z';
update workflow_inbox set dead_lettered_at=substr(dead_lettered_at,1,19)||'.'||substr((case when substr(dead_lettered_at,20,1)='.' then substr(dead_lettered_at,21,length(dead_lettered_at)-21) else '' end)||'000000000',1,9)||'Z' where dead_lettered_at is not null and length(dead_lettered_at)<>30 and dead_lettered_at like '____-__-__T__:__:__%Z';
update workflow_outbox set created_at=substr(created_at,1,19)||'.'||substr((case when substr(created_at,20,1)='.' then substr(created_at,21,length(created_at)-21) else '' end)||'000000000',1,9)||'Z' where created_at is not null and length(created_at)<>30 and created_at like '____-__-__T__:__:__%Z';
update workflow_outbox set published_at=substr(published_at,1,19)||'.'||substr((case when substr(published_at,20,1)='.' then substr(published_at,21,length(published_at)-21) else '' end)||'000000000',1,9)||'Z' where published_at is not null and length(published_at)<>30 and published_at like '____-__-__T__:__:__%Z';
update workflow_outbox set next_attempt_at=substr(next_attempt_at,1,19)||'.'||substr((case when substr(next_attempt_at,20,1)='.' then substr(next_attempt_at,21,length(next_attempt_at)-21) else '' end)||'000000000',1,9)||'Z' where next_attempt_at is not null and length(next_attempt_at)<>30 and next_attempt_at like '____-__-__T__:__:__%Z';
update workflow_outbox set claim_until=substr(claim_until,1,19)||'.'||substr((case when substr(claim_until,20,1)='.' then substr(claim_until,21,length(claim_until)-21) else '' end)||'000000000',1,9)||'Z' where claim_until is not null and length(claim_until)<>30 and claim_until like '____-__-__T__:__:__%Z';
update workflow_outbox set dead_lettered_at=substr(dead_lettered_at,1,19)||'.'||substr((case when substr(dead_lettered_at,20,1)='.' then substr(dead_lettered_at,21,length(dead_lettered_at)-21) else '' end)||'000000000',1,9)||'Z' where dead_lettered_at is not null and length(dead_lettered_at)<>30 and dead_lettered_at like '____-__-__T__:__:__%Z';
update workflow_timer set due_at=substr(due_at,1,19)||'.'||substr((case when substr(due_at,20,1)='.' then substr(due_at,21,length(due_at)-21) else '' end)||'000000000',1,9)||'Z' where due_at is not null and length(due_at)<>30 and due_at like '____-__-__T__:__:__%Z';
update workflow_timer set created_at=substr(created_at,1,19)||'.'||substr((case when substr(created_at,20,1)='.' then substr(created_at,21,length(created_at)-21) else '' end)||'000000000',1,9)||'Z' where created_at is not null and length(created_at)<>30 and created_at like '____-__-__T__:__:__%Z';
update workflow_timer set next_attempt_at=substr(next_attempt_at,1,19)||'.'||substr((case when substr(next_attempt_at,20,1)='.' then substr(next_attempt_at,21,length(next_attempt_at)-21) else '' end)||'000000000',1,9)||'Z' where next_attempt_at is not null and length(next_attempt_at)<>30 and next_attempt_at like '____-__-__T__:__:__%Z';
update workflow_timer set claim_until=substr(claim_until,1,19)||'.'||substr((case when substr(claim_until,20,1)='.' then substr(claim_until,21,length(claim_until)-21) else '' end)||'000000000',1,9)||'Z' where claim_until is not null and length(claim_until)<>30 and claim_until like '____-__-__T__:__:__%Z';
update workflow_timer set updated_at=substr(updated_at,1,19)||'.'||substr((case when substr(updated_at,20,1)='.' then substr(updated_at,21,length(updated_at)-21) else '' end)||'000000000',1,9)||'Z' where updated_at is not null and length(updated_at)<>30 and updated_at like '____-__-__T__:__:__%Z';
update workflow_lock set expires_at=substr(expires_at,1,19)||'.'||substr((case when substr(expires_at,20,1)='.' then substr(expires_at,21,length(expires_at)-21) else '' end)||'000000000',1,9)||'Z' where expires_at is not null and length(expires_at)<>30 and expires_at like '____-__-__T__:__:__%Z';
update workflow_inbox_attempt set created_at=substr(created_at,1,19)||'.'||substr((case when substr(created_at,20,1)='.' then substr(created_at,21,length(created_at)-21) else '' end)||'000000000',1,9)||'Z' where created_at is not null and length(created_at)<>30 and created_at like '____-__-__T__:__:__%Z';
update workflow_outbox_attempt set created_at=substr(created_at,1,19)||'.'||substr((case when substr(created_at,20,1)='.' then substr(created_at,21,length(created_at)-21) else '' end)||'000000000',1,9)||'Z' where created_at is not null and length(created_at)<>30 and created_at like '____-__-__T__:__:__%Z';
update workflow_timer_attempt set created_at=substr(created_at,1,19)||'.'||substr((case when substr(created_at,20,1)='.' then substr(created_at,21,length(created_at)-21) else '' end)||'000000000',1,9)||'Z' where created_at is not null and length(created_at)<>30 and created_at like '____-__-__T__:__:__%Z';
update workflow_command_result set created_at=substr(created_at,1,19)||'.'||substr((case when substr(created_at,20,1)='.' then substr(created_at,21,length(created_at)-21) else '' end)||'000000000',1,9)||'Z' where created_at is not null and length(created_at)<>30 and created_at like '____-__-__T__:__:__%Z';
