package org.jworkflow.jdbc;

import org.jworkflow.engine.*;import org.jworkflow.events.*;import org.jworkflow.model.*;import org.jworkflow.outbox.*;
import java.nio.file.*;import java.sql.*;import java.time.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;

public final class JdbcOutboxLifecycleTest {
    public static void main(String[]args)throws Exception{atomicEnqueueAndRollback();atomicSnapshotEventTimerAndOutboxCommit();successfulPublicationRunsOutsideTransaction();failureRetryPreservesLogicalMessage();deadLetterAndManualRepublish();competingWorkersAndExpiredClaims();brokerAcceptanceCrashRedeliversSameIdempotencyKey();routingPreservesEnvelope();}
    private static void atomicEnqueueAndRollback()throws Exception{Fixture f=fixture("atomic",5);try(JdbcWorkflowEngine engine=engine(f,definition())){engine.start("outbox-flow","atomic-ok",Map.of());check(count(f,"workflow_instance")==1&&count(f,"workflow_event")==1&&count(f,"workflow_outbox")==1,"state event and outbox must commit atomically");engine.writeProbe(stage->{if("outbox".equals(stage))throw new IllegalStateException("after outbox");});try{engine.start("outbox-flow","atomic-fail",Map.of());throw new AssertionError("expected rollback");}catch(IllegalStateException expected){}check(count(f,"workflow_instance")==1&&count(f,"workflow_event")==1&&count(f,"workflow_outbox")==1,"rollback must leave no workflow event or outbox fragment");}}
    private static void atomicSnapshotEventTimerAndOutboxCommit()throws Exception{Fixture f=fixture("atomic-timer",5);WorkflowDefinition timed=WorkflowDefinition.of("timed-outbox","1","waiting",WorkflowNode.waitFor("waiting",new WaitDefinition(new EventName("approval.received"),"businessKey","done"),new TimeoutDefinition(Duration.ofMinutes(5),"done",new EventName("approval.expired"))),WorkflowNode.end("done"));try(JdbcWorkflowEngine engine=engine(f,timed)){engine.start("timed-outbox","timer-order",Map.of());check(count(f,"workflow_instance")==1&&count(f,"workflow_event")==1&&count(f,"workflow_timer")==1&&count(f,"workflow_outbox")==1,"snapshot event timer and outbox must share one commit");}}
    private static void successfulPublicationRunsOutsideTransaction()throws Exception{Fixture f=fixture("success",5);try(JdbcWorkflowEngine engine=engine(f,definition())){engine.start("outbox-flow","success",Map.of());UUID id=outboxId(f);AtomicBoolean outside=new AtomicBoolean();AtomicReference<OutboxMessage> delivered=new AtomicReference<>();try(JdbcOutboxApplication app=engine.outbox(Map.of("workflow.events",message->{outside.set(engine.connectionFactory().currentTransactionConnection()==null);delivered.set(message);} ))){check(app.pollOnce()==1,"one message must publish");OutboxMessage stored=app.find(id).orElseThrow();check(outside.get()&&stored.status()==OutboxMessageStatus.PUBLISHED,"network call must be outside transaction and finalize published");check(app.attempts(id).size()==1&&app.attempts(id).get(0).status()==OutboxMessageStatus.PUBLISHED,"success attempt must append");check(delivered.get().idempotencyKey().equals(stored.idempotencyKey()),"publisher must receive durable idempotency key");}}}
    private static void failureRetryPreservesLogicalMessage()throws Exception{Fixture f=fixture("retry",3);try(JdbcWorkflowEngine engine=engine(f,definition())){engine.start("outbox-flow","retry",Map.of());UUID id=outboxId(f);AtomicInteger calls=new AtomicInteger();List<OutboxMessage> deliveries=new ArrayList<>();try(JdbcOutboxApplication app=engine.outbox(Map.of("workflow.events",message->{deliveries.add(message);if(calls.getAndIncrement()==0)throw new IllegalStateException("broker unavailable");}))){app.pollOnce();OutboxMessage retry=app.find(id).orElseThrow();check(retry.status()==OutboxMessageStatus.RETRY_SCHEDULED&&retry.messageId().equals(id),"failure must schedule the same logical message");check("application/json".equals(retry.message().contentType())||retry.message().contentType()==null,"message metadata must remain readable");f.clock.advance(Duration.ofSeconds(2));app.pollOnce();OutboxMessage published=app.find(id).orElseThrow();check(published.status()==OutboxMessageStatus.PUBLISHED&&app.attempts(id).size()==2,"retry must publish without another logical outbox row");check(deliveries.get(0).idempotencyKey().equals(deliveries.get(1).idempotencyKey())&&count(f,"workflow_outbox")==1,"retry must retain idempotency identity");}}}
    private static void deadLetterAndManualRepublish()throws Exception{Fixture f=fixture("dead",2);UUID id;try(JdbcWorkflowEngine engine=engine(f,definition())){engine.start("outbox-flow","dead",Map.of());id=outboxId(f);try(JdbcOutboxApplication failing=engine.outbox(Map.of("workflow.events",m->{throw new IllegalStateException("down");}))){failing.pollOnce();f.clock.advance(Duration.ofSeconds(2));failing.pollOnce();check(failing.find(id).orElseThrow().status()==OutboxMessageStatus.DEAD_LETTER,"exhausted publication must dead-letter");check(failing.attempts(id).size()==2,"dead-letter must preserve each immutable attempt");}try(JdbcOutboxApplication recovered=engine.outbox(Map.of("workflow.events",m->{}))){OutboxMessage result=recovered.republish(new RepublishOutboxMessageCommand(id,"operator","broker restored",f.clock.instant()));check(result.status()==OutboxMessageStatus.PUBLISHED&&result.messageId().equals(id),"manual republish must reuse dead-letter row");check(recovered.attempts(id).size()==3,"manual republish must append history");try{recovered.republish(new RepublishOutboxMessageCommand(id,"operator","duplicate",f.clock.instant()));throw new AssertionError("published message must not be manually requeued");}catch(OutboxRepublishException expected){}}}}
    private static void competingWorkersAndExpiredClaims()throws Exception{Fixture f=fixture("claims",5);try(JdbcWorkflowEngine seed=engine(f,definition())){seed.start("outbox-flow","claim",Map.of());}AtomicInteger published=new AtomicInteger();try(JdbcWorkflowEngine one=engine(f,null);JdbcWorkflowEngine two=engine(f,null);JdbcOutboxApplication a=one.outbox(Map.of("workflow.events",m->published.incrementAndGet()));JdbcOutboxApplication b=two.outbox(Map.of("workflow.events",m->published.incrementAndGet()))){ExecutorService pool=Executors.newFixedThreadPool(2);try{Future<Integer>x=pool.submit(a::pollOnce),y=pool.submit(b::pollOnce);check(x.get()+y.get()==1,"competing workers must claim once");}finally{pool.shutdownNow();}check(published.get()==1,"one claim must produce one publication");}
        Fixture crash=fixture("expired",5);UUID id;try(JdbcWorkflowEngine seed=engine(crash,definition())){seed.start("outbox-flow","expired",Map.of());id=outboxId(crash);}JdbcWorkflowPersistence ports=JdbcWorkflowPersistence.create(crash.url,null,null,null,null,false,Map.of());ports.jdbcTransactions().inImmediateTransaction(()->ports.outbox().claimEligible(crash.clock.instant(),"crashed",crash.clock.instant().plusSeconds(5),1));try(JdbcWorkflowEngine before=engine(crash,null);JdbcOutboxApplication app=before.outbox(Map.of("workflow.events",m->{}))){check(app.pollOnce()==0,"valid outbox lease must not be stolen");}crash.clock.advance(Duration.ofSeconds(6));try(JdbcWorkflowEngine after=engine(crash,null);JdbcOutboxApplication app=after.outbox(Map.of("workflow.events",m->{}))){check(app.pollOnce()==1&&app.find(id).orElseThrow().status()==OutboxMessageStatus.PUBLISHED,"expired outbox claim must recover");}}
    private static void brokerAcceptanceCrashRedeliversSameIdempotencyKey()throws Exception{Fixture f=fixture("atleastonce",5);UUID id;try(JdbcWorkflowEngine seed=engine(f,definition())){seed.start("outbox-flow","redelivery",Map.of());id=outboxId(f);}JdbcWorkflowPersistence ports=JdbcWorkflowPersistence.create(f.url,null,null,null,null,false,Map.of());OutboxMessage claimed=ports.jdbcTransactions().inImmediateTransaction(()->ports.outbox().claimEligible(f.clock.instant(),"crashed-after-accept",f.clock.instant().plusSeconds(5),1)).get(0);List<String> brokerKeys=new ArrayList<>();brokerKeys.add(claimed.idempotencyKey());f.clock.advance(Duration.ofSeconds(6));try(JdbcWorkflowEngine recovered=engine(f,null);JdbcOutboxApplication app=recovered.outbox(Map.of("workflow.events",m->brokerKeys.add(m.idempotencyKey())))){app.pollOnce();check(app.find(id).orElseThrow().status()==OutboxMessageStatus.PUBLISHED,"expired post-accept claim must redeliver");check(brokerKeys.size()==2&&brokerKeys.get(0).equals(brokerKeys.get(1)),"at-least-once redelivery must use the same idempotency key");}}
    private static void routingPreservesEnvelope(){Instant now=Instant.parse("2026-01-01T00:00:00Z");WorkflowEvent event=new WorkflowEvent(new EventMetadata(null,new EventName("order.created"),"orders","corr","cause","trace",null,"business","tenant","4",now,now,Map.of("h","v")),new EventMessage(Map.of("amount",12),"application/json","order","3",false,Map.of("a","b")));OutboxMessage routed=new OutboxRoutingService(e->List.of("orders.topic")).route(event).get(0);check(routed.message().equals(new EventMessage(Map.of("amount",12),"application/json","order","3",false,Map.of("a","b","eventName","order.created","sourceSystem","orders","taxonomyVersion","4")))&&"corr".equals(routed.correlationId())&&"cause".equals(routed.causationId()),"routing must preserve complete envelope metadata");}
    private static WorkflowDefinition definition(){return WorkflowDefinition.of("outbox-flow","1","pending",WorkflowNode.step("pending","work.do",List.of(WorkflowTransition.goTo("done"))),WorkflowNode.end("done"));}
    private static JdbcWorkflowEngine engine(Fixture f,WorkflowDefinition definition)throws Exception{WorkflowEngineBuilder b=WorkflowEngine.builder().type(WorkflowEngine.Type.SQLITE).jdbcUrl(f.url).initialize(true).clock(f.clock).timerPolling(false).setting("outbox.max-attempts",Integer.toString(f.maxAttempts)).setting("outbox.retry-initial-ms","1000").setting("outbox.retry-maximum-ms","5000");if(definition!=null)b.definition(definition);return(JdbcWorkflowEngine)b.build();}
    private static UUID outboxId(Fixture f)throws Exception{try(Connection c=DriverManager.getConnection(f.url);Statement s=c.createStatement();ResultSet r=s.executeQuery("select id from workflow_outbox order by created_at,id limit 1")){if(!r.next())throw new AssertionError("missing outbox row");return UUID.fromString(r.getString(1));}}private static int count(Fixture f,String table)throws Exception{try(Connection c=DriverManager.getConnection(f.url);Statement s=c.createStatement();ResultSet r=s.executeQuery("select count(*) from "+table)){return r.next()?r.getInt(1):0;}}
    private static Fixture fixture(String name,int max)throws Exception{return new Fixture("jdbc:sqlite:"+Files.createTempFile("jworkflow-outbox-"+name+"-",".sqlite").toAbsolutePath(),new MutableClock(Instant.parse("2026-01-01T00:00:00Z")),max);}private record Fixture(String url,MutableClock clock,int maxAttempts){}private static final class MutableClock extends Clock{private Instant now;MutableClock(Instant now){this.now=now;}void advance(Duration d){now=now.plus(d);}@Override public ZoneId getZone(){return ZoneOffset.UTC;}@Override public Clock withZone(ZoneId z){return this;}@Override public Instant instant(){return now;}}private static void check(boolean value,String message){if(!value)throw new AssertionError(message);}
    @org.junit.jupiter.api.Test
    void junitContract() {
        org.junit.jupiter.api.Assertions.assertDoesNotThrow(() -> main(new String[0]));
    }
}
